#!/bin/sh

# accountNumber=$(grep 'accountNumber: \d*' republic-config.js | grep -o '\d\+')
accountNumber=${1:-10}
echo "Starting with $accountNumber accounts..."

ganache-cli --accounts $accountNumber -d --acctKeys ./test/_helpers/privateKeys.json --gasLimit 0xfffffffffff
#$(npm bin)/ganache-cli
