#!/bin/sh

# accountNumber=$(grep 'accountNumber: \d*' republic-config.js | grep -o '\d\+')
accountNumber=${1:-10}
echo "Starting with $accountNumber accounts..."

$(npm bin)/ganache-cli --accounts $accountNumber --seed republic --acctKeys ./test/privateKeys.json
